# Exercise 1 - Computational Graph sigmoid

In [1]:
%load_ext tensorboard
import tensorflow as tf
import numpy as np

logdir = 'logs/'
writer = tf.summary.create_file_writer(logdir)
tf.summary.trace_on(graph=True, profiler=True)

Instructions for updating:
use `tf.profiler.experimental.start` instead.


In [2]:
import tensorflow as tf

In [3]:
@tf.function
def build():
    x1 = tf.constant(1, dtype=tf.float32)
    x2 = tf.constant(2, dtype=tf.float32)
    w1 = tf.constant(3, dtype=tf.float32)
    w2 = tf.constant(4, dtype=tf.float32)
    b = tf.constant(5, dtype=tf.float32)

    z = -(w1*x1+w2*x2+b)
    a = 1 / (1 + tf.math.exp(z))
    return tf.gradients(ys=a, xs=[x1, w1, x2, w2])

build()

[<tf.Tensor: shape=(), dtype=float32, numpy=3.3760546e-07>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.1253515e-07>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.501406e-07>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.250703e-07>]

![](graph.png)

In [5]:
with writer.as_default():
    tf.summary.trace_export(
        name='NN',
        step=0,
        profiler_outdir=logdir)

%tensorboard --logdir logs/

Instructions for updating:
use `tf.profiler.experimental.stop` instead.
Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.
Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.


Reusing TensorBoard on port 6006 (pid 15264), started 0:04:39 ago. (Use '!kill 15264' to kill it.)

As we can see, tensorflow also included the gra